name: CI Quality Lab

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'  # ✅ CORREGIDO: distribución especificada
        cache: 'maven'
        
    - name: Build and run tests with Maven
      run: |
        cd backend
        mvn clean verify -DskipTests=false
      
    - name: Run Newman tests (API)
      run: |
        npm install -g newman
        newman run tests/postman/QualityLab.postman_collection.json
      
    - name: Upload JaCoCo report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: backend/target/site/jacoco/  # ✅ Ruta corregida
        retention-days: 30
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: backend/target/surefire-reports/
        retention-days: 30
